name: Rails CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  development_ci:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: practice_record_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: 127.0.0.1

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      env:
        RAILS_ENV: test
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Clear Rails cache
      run: rm -rf tmp/cache/assets

    - name: Precompile assets
      env:
        RAILS_ENV: test
      run: bundle exec rake assets:precompile

    - name: Run Brakeman
      run: bundle exec brakeman

    - name: Run tests
      env:
        RAILS_ENV: test
      run: bundle exec rspec
