name: Rails CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      env:
        RAILS_ENV: test
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run tests
      env:
        RAILS_ENV: test
      run: bundle exec rspec
